version: 2.1
orbs:
  cypress: cypress-io/cypress@1

jobs:
  build:
    docker:
      - image: circleci/node:12

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Build docker dev image
          command: |
            docker build -t "kidsfirstdrc/kf-ui-fhir-data-dashboard:dev" \
                         -t "kidsfirstdrc/kf-ui-fhir-data-dashboard:latest" .

      - run:
          name: Build docker kidsfirst image
          command: |
            if [ $CIRCLE_BRANCH == 'master' ]; then
                docker build \
                      --build-arg REACT_APP_FHIR_API_NAME="Kids First" \
                      --build-arg REACT_APP_FHIR_API="http://10.10.1.141:8000/" \
                      -t "kidsfirstdrc/kf-ui-fhir-data-dashboard:kidsfirst" .
            fi
      - run:
          name: 'Push docker images'
          command: |
            if [ $CIRCLE_BRANCH == 'master' ]; then
                GIT_COMMIT=$(git rev-parse HEAD)
                docker login -u $KF_DOCKER_HUB_USER -p $KF_DOCKER_HUB_PW
                docker tag kidsfirstdrc/kf-ui-fhir-data-dashboard:dev \
                           kidsfirstdrc/kf-ui-fhir-data-dashboard:$GIT_COMMIT
                docker push kidsfirstdrc/kf-ui-fhir-data-dashboard:dev
                docker push kidsfirstdrc/kf-ui-fhir-data-dashboard:latest
                docker push kidsfirstdrc/kf-ui-fhir-data-dashboard:kidsfirst
                docker push kidsfirstdrc/kf-ui-fhir-data-dashboard:$GIT_COMMIT
            fi

workflows:
  build_and_test:
    jobs:
      - cypress/install:
          build: 'npm run build'
      - cypress/run:
          requires:
            - cypress/install
          start: 'npm start'
      - build
