version: 2.1
orbs:
  cypress: cypress-io/cypress@1

jobs:
  build:
    docker:
      - image: circleci/node:12

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Build docker images
          command: |
            docker build -t "kidsfirstdrc/ncpi-ui-fhir-data-dashboard:dev" \
                         -t "kidsfirstdrc/ncpi-ui-fhir-data-dashboard:latest" .

      - run:
          name: 'Push docker images'
          command: |
            if [ $CIRCLE_BRANCH == 'master' ]; then
                GIT_COMMIT=$(git rev-parse HEAD)
                docker login -u $KF_DOCKER_HUB_USER -p $KF_DOCKER_HUB_PW
                docker tag kidsfirstdrc/ncpi-ui-fhir-data-dashboard:dev \
                           kidsfirstdrc/ncpi-ui-fhir-data-dashboard:$GIT_COMMIT
                docker push kidsfirstdrc/ncpi-ui-fhir-data-dashboard:dev
                docker push kidsfirstdrc/ncpi-ui-fhir-data-dashboard:latest
                docker push kidsfirstdrc/ncpi-ui-fhir-data-dashboard:$GIT_COMMIT
            fi

workflows:
  build_and_test:
    jobs:
      - cypress/install:
          build: 'npm run build'
      - cypress/run:
          requires:
            - cypress/install
          executor: cypress/browsers-chrome69
          browser: chrome
          start: 'npm start'
      - build:
          requires:
            - cypress/run
