export const mobileWidth = 425;
export const tabletWidth = 768;

export const NO_AUTH = 'NO_AUTH';
export const BASIC_AUTH = 'BASIC_AUTH';

export const getBaseUrl = () => {
  let envVar = window.Cypress
    ? 'http://hapi.fhir.org/baseR4/'
    : window._env_.REACT_APP_FHIR_API;
  if (envVar) {
    if (envVar.substring(envVar.length - 1, envVar.length) !== '/') {
      envVar = envVar.concat('/');
    }
    return envVar;
  }
  return null;
};

const getDefaultFhirServers = () => {
  const envVar = getBaseUrl();
  let servers = [
    {
      id: 0,
      name: 'HAPI',
      url: 'http://hapi.fhir.org/baseR4/',
      authType: NO_AUTH,
    },
    {
      id: 1,
      name: 'Phenopackets',
      url: 'http://10.10.1.191:8000/',
      authType: BASIC_AUTH,
    },
    {
      id: 2,
      name: 'Kids First',
      url: 'http://10.10.1.141:8000/',
      authType: BASIC_AUTH,
    },
  ];
  if (envVar && servers.findIndex(x => x.url === envVar) < 0) {
    servers.push({
      id: servers.length,
      name: window._env_.REACT_APP_FHIR_API_NAME || envVar,
      url: envVar,
      authType: window._env_.REACT_APP_FHIR_API_AUTH_TYPE || NO_AUTH,
    });
  }
  return servers;
};

export const defaultFhirServers = getDefaultFhirServers();

export const oAuthUrl = 'https://syntheticmass.mitre.org/oauth2/accesstoken';

export const shouldUseProxyUrl = url =>
  url.includes('hapi') || url.includes('synthea') || url.includes('ncpi');

export const proxyUrl = 'https://damp-castle-44220.herokuapp.com/';
export const fhirUrl = 'http://hl7.org/fhir/StructureDefinition/';
export const defaultTableFields = ['id'];

export const eventOfInterest = {
  resourceType: window._env_.REACT_APP_EVENT_OF_INTEREST_TYPE || null,
  code: window._env_.REACT_APP_EVENT_OF_INTEREST_CODE || null,
  title: window._env_.REACT_APP_EVENT_OF_INTEREST_TITLE || '',
};

export const acceptedResourceTypes = new Set([
  'Account',
  'ActivityDefinition',
  'AdverseEvent',
  'AllergyIntolerance',
  'Appointment',
  'AppointmentResponse',
  'AuditEvent',
  'Basic',
  'Binary',
  'BiologicallyDerivedProduct',
  'BodyStructure',
  'CapabilityStatement',
  'CarePlan',
  'CareTeam',
  'CatalogEntry',
  'ChargeItem',
  'ChargeItemDefinition',
  'Claim',
  'ClaimResponse',
  'ClinicalImpression',
  'CodeSystem',
  'Communication',
  'CommunicationRequest',
  'CompartmentDefinition',
  'Composition',
  'ConceptMap',
  'Condition',
  'Consent',
  'Contract',
  'Coverage',
  'CoverageEligibilityRequest',
  'CoverageEligibilityResponse',
  'DetectedIssue',
  'Device',
  'DeviceDefinition',
  'DeviceMetric',
  'DeviceRequest',
  'DeviceUseStatement',
  'DiagnosticReport',
  'DocumentManifest',
  'DocumentReference',
  'EffectEvidenceSynthesis',
  'Encounter',
  'Endpoint',
  'EnrollmentRequest',
  'EnrollmentResponse',
  'EpisodeOfCare',
  'EventDefinition',
  'Evidence',
  'EvidenceVariable',
  'ExampleScenario',
  'ExplanationOfBenefit',
  'FamilyMemberHistory',
  'Flag',
  'Goal',
  'GraphDefinition',
  'Group',
  'GuidanceResponse',
  'HealthcareService',
  'ImagingStudy',
  'Immunization',
  'ImmunizationEvaluation',
  'ImmunizationRecommendation',
  'ImplementationGuide',
  'InsurancePlan',
  'Invoice',
  'Library',
  'Linkage',
  'List',
  'Location',
  'Measure',
  'MeasureReport',
  'Media',
  'Medication',
  'MedicationAdministration',
  'MedicationDispense',
  'MedicationKnowledge',
  'MedicationRequest',
  'MedicationStatement',
  'MedicinalProduct',
  'MedicinalProductAuthorization',
  'MedicinalProductContraindication',
  'MedicinalProductIndication',
  'MedicinalProductIngredient',
  'MedicinalProductInteraction',
  'MedicinalProductManufactured',
  'MedicinalProductPackaged',
  'MedicinalProductPharmaceutical',
  'MedicinalProductUndesirableEffect',
  'MessageDefinition',
  'MessageHeader',
  'MolecularSequence',
  'NamingSystem',
  'NutritionOrder',
  'Observation',
  'ObservationDefinition',
  'OperationDefinition',
  'OperationOutcome',
  'Organization',
  'OrganizationAffiliation',
  'Parameters',
  'Patient',
  'PaymentNotice',
  'PaymentReconciliation',
  'Person',
  'PlanDefinition',
  'Practitioner',
  'PractitionerRole',
  'Procedure',
  'Provenance',
  'Questionnaire',
  'QuestionnaireResponse',
  'RelatedPerson',
  'RequestGroup',
  'ResearchDefinition',
  'ResearchElementDefinition',
  'ResearchStudy',
  'ResearchSubject',
  'RiskAssessment',
  'RiskEvidenceSynthesis',
  'Schedule',
  'SearchParameter',
  'ServiceRequest',
  'Slot',
  'Specimen',
  'SpecimenDefinition',
  'StructureDefinition',
  'StructureMap',
  'Subscription',
  'Substance',
  'SubstanceNucleicAcid',
  'SubstancePolymer',
  'SubstanceProtein',
  'SubstanceReferenceInformation',
  'SubstanceSourceMaterial',
  'SubstanceSpecification',
  'SupplyDelivery',
  'SupplyRequest',
  'Task',
  'TerminologyCapabilities',
  'TestReport',
  'TestScript',
  'ValueSet',
  'VerificationResult',
  'VisionPrescription',
]);

export const resourceCategories = {
  CapabilityStatement: ['Foundation', 'Conformance'],
  StructureDefinition: ['Foundation', 'Conformance'],
  ImplementationGuide: ['Foundation', 'Conformance'],
  SearchParameter: ['Foundation', 'Conformance'],
  MessageDefinition: ['Foundation', 'Conformance'],
  OperationDefinition: ['Foundation', 'Conformance'],
  CompartmentDefinition: ['Foundation', 'Conformance'],
  StructureMap: ['Foundation', 'Conformance'],
  GraphDefinition: ['Foundation', 'Conformance'],
  ExampleScenario: ['Foundation', 'Conformance'],
  CodeSystem: ['Foundation', 'Terminology'],
  ValueSet: ['Foundation', 'Terminology'],
  ConceptMap: ['Foundation', 'Terminology'],
  NamingSystem: ['Foundation', 'Terminology'],
  TerminologyCapabilities: ['Foundation', 'Terminology'],
  Provenance: ['Foundation', 'Security'],
  AuditEvent: ['Foundation', 'Security'],
  Consent: ['Foundation', 'Security'],
  Composition: ['Foundation', 'Documents'],
  DocumentManifest: ['Foundation', 'Documents'],
  DocumentReference: ['Foundation', 'Documents'],
  CatalogEntry: ['Foundation', 'Documents'],
  Basic: ['Foundation', 'Other'],
  Binary: ['Foundation', 'Other'],
  Bundle: ['Foundation', 'Other'],
  Linkage: ['Foundation', 'Other'],
  MessageHeader: ['Foundation', 'Other'],
  OperationOutcome: ['Foundation', 'Other'],
  Parameters: ['Foundation', 'Other'],
  Subscription: ['Foundation', 'Other'],
  Patient: ['Base', 'Individuals'],
  Practitioner: ['Base', 'Individuals'],
  PractitionerRole: ['Base', 'Individuals'],
  RelatedPerson: ['Base', 'Individuals'],
  Person: ['Base', 'Individuals'],
  Group: ['Base', 'Individuals'],
  Organization: ['Base', 'Entities 1'],
  OrganizationAffiliation: ['Base', 'Entities 1'],
  HealthcareService: ['Base', 'Entities 1'],
  Endpoint: ['Base', 'Entities 1'],
  Location: ['Base', 'Entities 1'],
  Substance: ['Base', 'Entities 2'],
  BiologicallyDerivedProduct: ['Base', 'Entities 2'],
  Device: ['Base', 'Entities 2'],
  DeviceMetric: ['Base', 'Entities 2'],
  Task: ['Base', 'Workflow'],
  Appointment: ['Base', 'Workflow'],
  AppointmentResponse: ['Base', 'Workflow'],
  Schedule: ['Base', 'Workflow'],
  Slot: ['Base', 'Workflow'],
  VerificationResult: ['Base', 'Workflow'],
  Encounter: ['Base', 'Management'],
  EpisodeOfCare: ['Base', 'Management'],
  Flag: ['Base', 'Management'],
  List: ['Base', 'Management'],
  Library: ['Base', 'Management'],
  AllergyIntolerance: ['Clinical', 'Summary'],
  AdverseEvent: ['Clinical', 'Summary'],
  Condition: ['Clinical', 'Summary'],
  Procedure: ['Clinical', 'Summary'],
  FamilyMemberHistory: ['Clinical', 'Summary'],
  ClinicalImpression: ['Clinical', 'Summary'],
  DetectedIssue: ['Clinical', 'Summary'],
  Observation: ['Clinical', 'Diagnostics'],
  Media: ['Clinical', 'Diagnostics'],
  DiagnosticReport: ['Clinical', 'Diagnostics'],
  Specimen: ['Clinical', 'Diagnostics'],
  BodyStructure: ['Clinical', 'Diagnostics'],
  ImagingStudy: ['Clinical', 'Diagnostics'],
  QuestionnaireResponse: ['Clinical', 'Diagnostics'],
  MolecularSequence: ['Clinical', 'Diagnostics'],
  MedicationRequest: ['Clinical', 'Medications'],
  MedicationAdministration: ['Clinical', 'Medications'],
  MedicationDispense: ['Clinical', 'Medications'],
  MedicationStatement: ['Clinical', 'Medications'],
  Medication: ['Clinical', 'Medications'],
  MedicationKnowledge: ['Clinical', 'Medications'],
  Immunization: ['Clinical', 'Medications'],
  ImmunizationEvaluation: ['Clinical', 'Medications'],
  ImmunizationRecommendation: ['Clinical', 'Medications'],
  CarePlan: ['Clinical', 'Care Provision'],
  CareTeam: ['Clinical', 'Care Provision'],
  Goal: ['Clinical', 'Care Provision'],
  ServiceRequest: ['Clinical', 'Care Provision'],
  NutritionOrder: ['Clinical', 'Care Provision'],
  VisionPrescription: ['Clinical', 'Care Provision'],
  RiskAssessment: ['Clinical', 'Care Provision'],
  RequestGroup: ['Clinical', 'Care Provision'],
  Communication: ['Clinical', 'Request & Response'],
  CommunicationRequest: ['Clinical', 'Request & Response'],
  DeviceRequest: ['Clinical', 'Request & Response'],
  DeviceUseStatement: ['Clinical', 'Request & Response'],
  GuidanceResponse: ['Clinical', 'Request & Response'],
  SupplyRequest: ['Clinical', 'Request & Response'],
  SupplyDelivery: ['Clinical', 'Request & Response'],
  Coverage: ['Financial', 'Support'],
  CoverageEligibilityRequest: ['Financial', 'Support'],
  CoverageEligibilityResponse: ['Financial', 'Support'],
  EnrollmentRequest: ['Financial', 'Support'],
  EnrollmentResponse: ['Financial', 'Support'],
  Claim: ['Financial', 'Billing'],
  ClaimResponse: ['Financial', 'Billing'],
  Invoice: ['Financial', 'Billing'],
  PaymentNotice: ['Financial', 'Payment'],
  PaymentReconciliation: ['Financial', 'Payment'],
  Account: ['Financial', 'General'],
  ChargeItem: ['Financial', 'General'],
  ChargeItemDefinition: ['Financial', 'General'],
  Contract: ['Financial', 'General'],
  ExplanationOfBenefit: ['Financial', 'General'],
  InsurancePlan: ['Financial', 'General'],
  ResearchStudy: ['Specialized', 'Public Health & Research'],
  ResearchSubject: ['Specialized', 'Public Health & Research'],
  ActivityDefinition: ['Specialized', 'Definitional Artifacts'],
  DeviceDefinition: ['Specialized', 'Definitional Artifacts'],
  EventDefinition: ['Specialized', 'Definitional Artifacts'],
  ObservationDefinition: ['Specialized', 'Definitional Artifacts'],
  PlanDefinition: ['Specialized', 'Definitional Artifacts'],
  Questionnaire: ['Specialized', 'Definitional Artifacts'],
  SpecimenDefinition: ['Specialized', 'Definitional Artifacts'],
  ResearchDefinition: ['Specialized', 'Evidence Based Medicine'],
  ResearchElementDefinition: ['Specialized', 'Evidence Based Medicine'],
  Evidence: ['Specialized', 'Evidence Based Medicine'],
  EvidenceVariable: ['Specialized', 'Evidence Based Medicine'],
  EffectEvidenceSynthesis: ['Specialized', 'Evidence Based Medicine'],
  RiskEvidenceSynthesis: ['Specialized', 'Evidence Based Medicine'],
  Measure: ['Specialized', 'Quality Reporting & Testing'],
  MeasureReport: ['Specialized', 'Quality Reporting & Testing'],
  TestScript: ['Specialized', 'Quality Reporting & Testing'],
  TestReport: ['Specialized', 'Quality Reporting & Testing'],
  MedicinalProduct: ['Specialized', 'Medication Definition'],
  MedicinalProductAuthorization: ['Specialized', 'Medication Definition'],
  MedicinalProductContraindication: ['Specialized', 'Medication Definition'],
  MedicinalProductIndication: ['Specialized', 'Medication Definition'],
  MedicinalProductIngredient: ['Specialized', 'Medication Definition'],
  MedicinalProductInteraction: ['Specialized', 'Medication Definition'],
  MedicinalProductManufactured: ['Specialized', 'Medication Definition'],
  MedicinalProductPackaged: ['Specialized', 'Medication Definition'],
  MedicinalProductPharmaceutical: ['Specialized', 'Medication Definition'],
  MedicinalProductUndesirableEffect: ['Specialized', 'Medication Definition'],
  SubstanceNucleicAcid: ['Specialized', 'Medication Definition'],
  SubstancePolymer: ['Specialized', 'Medication Definition'],
  SubstanceProtein: ['Specialized', 'Medication Definition'],
  SubstanceReferenceInformation: ['Specialized', 'Medication Definition'],
  SubstanceSpecification: ['Specialized', 'Medication Definition'],
  SubstanceSourceMaterial: ['Specialized', 'Medication Definition'],
};
